add 'single-node-production-edge' annotations to CVO manifests.
openshift/console-operator pull request #493
Opened 2020-12-06 14:46 UTC by osherdp

This adds annotations for the single-node-production-edge cluster profile. There's a growing requirement from several customers to enable creation of single-node (not high-available) Openshift clusters.
In stage one (following openshift/enhancements#504) there should be no implication on components logic.
In the next stage, the component's behavior will match a non high-availability profile if the customer is specifically interested in one.
This PR is separate from the 'single-node-developer' work, which will implement a different behavior and is currently on another stage of implementation.

For more info, please refer to the enhancement link and participate in the discussion.

2020-12-06 15:07 UTC, osherdp commented
/hold for openshift/api#813

2020-12-07 11:08 UTC, jhadvig requested changes
Thanks for this PR.
Could you please also add the annotation to the [/quickstarts](https://github.com/openshift/console-operator/tree/master/quickstarts) and also update it's [Readme](https://github.com/openshift/console-operator/blob/master/quickstarts/README.md) with the new annotation.
Thanks

2020-12-07 14:09 UTC, osherdp commented
/retest

2020-12-07 17:28 UTC, spadgett reviewed
Can you note that this annotation is required in the quickstarts README here?

https://github.com/openshift/console-operator/tree/master/quickstarts#contributing-quick-starts

2020-12-08 07:21 UTC, osherdp commented
@spadgett already did :)

2020-12-15 07:41 UTC, osherdp commented
Shifting strategy based on https://github.com/openshift/enhancements/pull/560

2020-12-15 07:41 UTC, closed without merging