[WIP] Bug 1954148: Implement console-operator updating Ingress operator config status with ComponentRoutes conditions
openshift/console-operator pull request #553
Opened 2021-06-10 10:12 UTC by jhadvig

Addressing per discussion with @awgreene, PTAL

FYI some methods have been borrowed from https://github.com/openshift/cluster-authentication-operator/pull/430/files, since the helpers for updating the status are still not available in library-go.

/assign @spadgett

2021-06-21 13:02 UTC, jhadvig commented
/bugzilla refresh

2021-06-21 13:54 UTC, awgreene requested changes
A few comments but it looks good otherwise.

2021-06-21 13:54 UTC, awgreene commented on manifests/03-rbac-role-cluster.yaml
> +  - create
I'm not convinced that this is needed but it's probably fine.

2021-06-21 13:54 UTC, awgreene commented on pkg/console/controllers/route/controller.go
> +	fmt.Printf("\nERROR - %q\n", err)
It seems like you typically use `klog`.

2021-06-21 13:54 UTC, awgreene commented on pkg/console/controllers/route/controller.go
> +		CurrentHostnames: []configv1.Hostname{configv1.Hostname(routeConfig.GetCustomRouteHostname())},
Seems like current hostname could be set to an empty string if [this defer statement](https://github.com/openshift/console-operator/pull/553/files#diff-af15b762c545564ccd44f8bf5c8592e4233e4836241f99b05bd73f8109c181daR323) is executed after the custom route fails validation.

2021-06-21 13:54 UTC, awgreene commented on pkg/console/controllers/route/controller.go
> +	// if routeConfig.IsCustomHostnameSet()
```suggestion
```

2022-01-21 04:07 UTC, yanpzhan commented
@jhadvig Seems the pr is ready for testing. I checked on cluster launched against the pr, after add custom route for "downloads" , the new created custom route could be accessed. In the ingress config yaml, there is condition:
    - conditions:
        - lastTransitionTime: '2022-01-21T03:32:54Z'
          message: 'Error Configuring custom route: [<nil>]'
          reason: CustomRouteError
          status: 'True'
          type: Degraded
        - lastTransitionTime: '2022-01-21T03:32:54Z'
          message: 'Error Configuring custom route: [<nil>]'
          reason: CustomRouteError
          status: 'False'
          type: Progressing
Check the whole yaml in http://pastebin.test.redhat.com/1023063 , is the condition correct?

2022-02-20 05:03 UTC, closed without merging