[WIP] CONSOLE-3063: PDB for console opds avoid too many replicas down
openshift/console-operator pull request #655
Opened 2022-05-27 13:13 UTC by cyril-ui-developer

2022-06-01 12:12 UTC, jhadvig reviewed
Adding couple of comments on the code structure and thoughs

Also in the `bindata/`folder I would rather use the full resource name, meaning `bindata/poddisruptionbudget/console.yaml`

2022-06-01 12:12 UTC, jhadvig commented on bindata/pdb/console-pdb.yaml
> +  name: console-pdb
We dont need to call instance after the resource, should just contain the name of the component
```suggestion
  name: console
```

2022-06-01 13:46 UTC, csrwng commented on manifests/07-operator-ibm-cloud-managed.yaml
>  # *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***
fwiw running `make update-bindata-assets` on the master branch has no impact on this file

2022-06-01 20:57 UTC, jhadvig commented on manifests/07-operator-ibm-cloud-managed.yaml
>  # *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***
Thanks @csrwng 
@cyril-ui-developer the file content was removed because you have compile errors in your go files.

2022-06-13 16:55 UTC, jhadvig requested changes
Thanks @cyril-ui-developer  the code looks really good 👍 
Adding a few comments.

2022-06-13 16:55 UTC, jhadvig commented on pkg/console/controllers/poddisruptionbudget/contrroller.go
> +	ctrl := &PodDisruptionBudgetController{
you are missing here the `pdbName` and `pdbClient`

2022-06-13 16:55 UTC, jhadvig commented on pkg/console/controllers/poddisruptionbudget/contrroller.go
> +func (c *PodDisruptionBudgetController) removePodDisruptionBudget(ctx context.Context, pdbName string) error {
no need to pass the name, you can use `c.pdbName` from the instance
```suggestion
func (c *PodDisruptionBudgetController) removePodDisruptionBudget(ctx context.Context) error {
```

2022-06-13 16:55 UTC, jhadvig commented on pkg/console/controllers/poddisruptionbudget/contrroller.go
> +	err := c.pdbClient.PodDisruptionBudgets(api.OpenShiftConsoleNamespace).Delete(ctx, pdbName, metav1.DeleteOptions{})
```suggestion
	err := c.pdbClient.PodDisruptionBudgets(api.OpenShiftConsoleNamespace).Delete(ctx, c.pdbName, metav1.DeleteOptions{})
```

2022-06-13 16:55 UTC, jhadvig commented on pkg/console/starter/starter.go
> +		kubeInformersNamespaced.Policy().V1().PodDisruptionBudgets(), // `openshift-console` namespace informers
please remove the `// 'openshift-console' namespace informers` comment

2022-06-17 13:38 UTC, jhadvig commented on test/e2e/util.go
> +	pdb, err := client.PodDisruptionBudget.PodDisruptionBudgets(consoleapi.OpenShiftConsoleNamespace).Patch(context.TODO(), consoleapi.OpenShiftConsoleRouteName, types.MergePatchType, []byte(`{"spec": {
we should be patching fields that are present in the PDB kind. `spec.port.targetPort` is Routes specific

2022-06-22 12:56 UTC, cyril-ui-developer commented
/retest

2022-06-22 16:39 UTC, cyril-ui-developer commented
@jhadvig Added `.MatchLabels` to `Selector`. However the e2e test is still failing. I'm seeing the error below in my local:
`TestEditUnmanagedPodDisruptionBudget
    unmanaged_test.go:12: waiting for setup to reach settled state...
    unmanaged_test.go:13: changing console operator state to 'Unmanaged'...
    util.go:120: patching Selector on the console PodDisruptionBudget
    unmanaged_test.go:86: error: poddisruptionbudgets.policy "console" not found
    unmanaged_test.go:18: waiting for cleanup to reach settled state...
--- FAIL: TestEditUnmanagedPodDisruptionBudget (5.91s)`

2022-06-23 17:59 UTC, ahardin-rh commented
/label docs-approved

2022-06-23 18:58 UTC, cyril-ui-developer commented
/retest-required

2022-06-23 23:41 UTC, cyril-ui-developer commented
/retest-required

2022-06-24 05:48 UTC, jhadvig commented
/retest

2022-06-24 06:50 UTC, yapei commented
/label qe-approved

2022-06-24 16:34 UTC, merged