export perspectives to console-config ConfigMap
openshift/console-operator pull request #678
Opened 2022-08-29 13:43 UTC by debsmita1

**Story:**
https://issues.redhat.com/browse/ODC-6783

Add dev catalog types customization API based on https://github.com/openshift/enhancements/pull/1205

Test setup:
This PR bumps the openshift/api, includes changes from https://github.com/openshift/api/pull/1269, and finally copies the data from the cluster Console configuration to the console-config ConfigMap.

To test this change launch a cluster with launch 

Open https://cluster/k8s/cluster/operator.openshift.io~v1~Console/cluster/yaml and configure customization like:
```
  customization:
    perspectives:
    - id: admin
       requiresAccessReview:
       - kind: Namespace
          verb: list
    - id: custom-admin
      state: Disabled
```
Open https://cluster/k8s/ns/openshift-console/configmaps/console-config and check the data key console-config.yaml. The YAML should contain the perspectives after a few seconds.

```
  customization:
    perspectives:
    - id: admin
       requiresAccessReview:
       - kind: Namespace
          verb: list
    - id: custom-admin
      state: Disabled
```

2022-08-29 13:46 UTC, debsmita1 commented
/assign @jerolimov

2022-09-02 06:22 UTC, invincibleJai commented
looks like it needs rebase

2022-09-08 12:26 UTC, debsmita1 commented
changing it to WIP as the API is not merged yet

2022-09-08 14:53 UTC, jerolimov commented
/retest

2022-09-08 15:30 UTC, jerolimov commented
/test unit

2022-09-08 15:30 UTC, jerolimov commented
/retest

2022-09-09 06:29 UTC, jerolimov commented
/retest

2022-09-16 12:26 UTC, debsmita1 commented
/test e2e-aws-operator

2022-09-16 17:39 UTC, debsmita1 commented
/retest

2022-09-19 06:02 UTC, debsmita1 commented
/retest

2022-09-19 07:36 UTC, jerolimov requested changes
Can we use singular here as well

2022-09-19 07:36 UTC, jerolimov commented on pkg/console/subresource/consoleserver/types.go
> +	Perspectives []Perspectives `yaml:"perspectives,omitempty"`
```suggestion
	Perspectives []Perspective `yaml:"perspectives,omitempty"`
```

2022-09-19 07:36 UTC, jerolimov commented on pkg/console/subresource/consoleserver/types.go
> +type Perspectives struct {
```suggestion
// Perspective allows enabling/disabling of perspective(s).
type Perspective struct {
```

2022-09-21 13:12 UTC, jerolimov commented on go.mod
> -)
:+1:

2022-09-21 13:14 UTC, jerolimov approved these changes
Tested this successfully on a cluster bot instance, together with https://github.com/openshift/console/pull/12075 :+1: 

Console ConfigMap was updated correctly.

/lgtm
/label qe-approved

2022-09-21 13:15 UTC, jerolimov commented
propagate from the Epic:
/label px-approved
/label docs-approved

/retest

2022-09-21 13:16 UTC, jerolimov commented
/assign @jhadvig @spadgett

2022-09-21 13:16 UTC, jerolimov commented
/retitle ODC-6783: Export perspectives to console-config ConfigMap

2022-09-21 13:33 UTC, jhadvig approved these changes
/approve

2022-09-21 16:25 UTC, merged