OCPBUGS-5836: Incorrect redirection when user try to download windows oc binary
openshift/console-operator pull request #727
Opened 2023-01-24 16:07 UTC by raspbeep

`os.path.basename()` did not remove windows executable extension `.exe`, was replaced by `os.path.basename(os.path.splitext(path)[0])` which first splits the path, takes the part before `.` and then passes it to the original `basename()` function.

/assign @jhadvig 
Signed-off-by: Pavel Kratochvil <pakratoc@redhat.com>

2023-01-24 16:23 UTC, spadgett commented
/ok-to-test

2023-01-24 16:28 UTC, jhadvig approved these changes
Tested the change on a live cluster, setting it to `Unmanaged` state and updating the `downloads` deployment

2023-01-24 16:29 UTC, jhadvig requested changes
The verify test if failing, please run `make update-bindata-assets` to update the changed bindata

2023-01-24 16:29 UTC, spadgett commented
/cc @yselkowitz

2023-01-24 16:30 UTC, jhadvig commented
/jira refresh

2023-01-24 16:44 UTC, jhadvig commented on pkg/console/assets/bindata.go
> +//
not sure why this is happening but these changes are not allowed by linter.
please remove them

2023-01-24 18:41 UTC, jhadvig commented on pkg/console/assets/bindata.go
> +//	data/
the script is switching spaces with tabs for some reason.. please put it back to spaces in order to satisfy the linter

2023-01-24 18:44 UTC, raspbeep commented
/retest

2023-01-25 05:52 UTC, yselkowitz commented
This doesn't seem quite right.  The Windows executable (whether downloaded uncompressed, or when extracted from the tarball or zip archives) still needs to have the `.exe` suffix, we just want to avoid that showing up in the compressed archives' names (oc.zip instead of oc.exe.zip etc.)

2023-01-25 08:47 UTC, raspbeep commented
/hold

2023-01-31 12:51 UTC, jhadvig commented
/label tide/merge-method-squash

2023-01-31 12:52 UTC, jhadvig commented
@yaacov could you please help review this fix? THank you! :)

2023-01-31 19:34 UTC, raspbeep commented
/retest

2023-02-01 01:26 UTC, yselkowitz approved these changes
/lgtm
/retest

2023-02-01 10:04 UTC, raspbeep commented
/retest

2023-02-01 12:23 UTC, raspbeep commented
/retest

2023-02-01 14:42 UTC, raspbeep commented
/retest

2023-02-01 22:52 UTC, raspbeep commented
/retest

2023-02-03 14:56 UTC, jhadvig commented
/hold cancel
/override ci/prow/e2e-aws-single-node

2023-02-06 07:58 UTC, jhadvig commented
/approved

2023-02-07 11:28 UTC, jhadvig commented
/retest

2023-02-07 15:37 UTC, jhadvig commented
/retest

2023-02-08 07:26 UTC, jhadvig commented
Overriding since the tests already [passed](https://github.com/openshift/console-operator/pull/727#issuecomment-1415993927z) but CI was retested.
/override ci/prow/e2e-aws-console

2023-02-16 14:24 UTC, jhadvig commented
/retest

2023-02-20 09:40 UTC, jhadvig commented
/test e2e-gcp-ovn

2023-02-20 11:43 UTC, merged