OCPBUGS-7116: Console operator should sync managed cluster 'controlPlaneTopology' field to managed cluster config
openshift/console-operator pull request #731
Opened 2023-02-07 19:31 UTC by jhadvig

Implemented per our discussion. The `controlPlaneTopology` will be part of the manages cluster config ConfigMap.

/assign @TheRealJon

2023-02-07 19:32 UTC, jhadvig commented
/jira refresh

2023-02-07 21:41 UTC, jhadvig commented
/retest

2023-02-08 07:47 UTC, jhadvig commented
/retest

2023-02-16 14:25 UTC, jhadvig commented
/retest

2023-02-20 15:15 UTC, TheRealJon requested changes
Missed a couple of name changes

2023-02-20 15:15 UTC, TheRealJon commented on pkg/console/controllers/advancedclustermanagement/managedclusters/controller.go
> +	errReason, err = c.SyncOLMConfigManagedClusterViews(ctx, operatorConfig, managedClusters)
```suggestion
	errReason, err = c.SyncInfrastructureConfigManagedClusterViews(ctx, operatorConfig, managedClusters)
```

2023-02-20 15:15 UTC, TheRealJon commented on pkg/console/controllers/advancedclustermanagement/managedclusters/controller.go
> +
Don't we need to fetch the infrastructure config MCV as we did for OLMConfig?
```suggestion
		// Check that managed cluster infrastructure config MCV has already been synced, skip if not found
		infraConfigMCV, err := c.dynamicClient.Resource(api.ManagedClusterViewGroupVersionResource).Namespace(clusterName).Get(ctx, api.InfrastructureConfigManagedClusterViewName, metav1.GetOptions{})
		if apierrors.IsNotFound(err) {
			klog.V(4).Infof("Infrastructure config ManagedClusterView not found for managed cluster %v", clusterName)
			continue
		}
		// Skip if unable to get olm config MCV for any other reason
		if err != nil {
			klog.V(4).Infof("Error getting Infrastructure config ManagedClusterView for managed cluster %v", clusterName)
			continue
		}
		controlPlaneTopology, err := managedclusterviewsub.GetInfrastructureConfigControlPlaneTopology(infraConfigMCV)
    if err != nil {
			klog.V(4).Infof("Error getting controlPlaneTopology field for managed cluster %v", clusterName)
			continue
		}
```

2023-02-20 15:15 UTC, TheRealJon commented on pkg/console/subresource/managedclusterview/infrastructure_config.go
> +	controlPlaneTopology, found, err := unstructured.NestedString(olmConfig.Object, "status", "result", "status", "controlPlaneTopology")
```suggestion
func GetInfrastructureConfigControlPlaneTopology(infraConfig *unstructured.Unstructured) (string, error) {
	controlPlaneTopology, found, err := unstructured.NestedString(infraConfig.Object, "status", "result", "status", "controlPlaneTopology")
```

2023-03-15 13:47 UTC, jhadvig commented
@TheRealJon comments addressed.
Please check last commit, also added some minor refactoring.

2023-04-20 09:23 UTC, jhadvig commented
Closing since we are going to remove the ACM related code.

cc'ing @TheRealJon

2023-04-20 09:23 UTC, closed without merging