OCPBUGS-25484: Bump library-go to deal with GET conflict
openshift/console-operator pull request #836
Opened 2024-01-15 12:34 UTC by jhadvig

Bumping library-go to pick up https://github.com/openshift/library-go/pull/1658 and adjusting `operatorclient` pkg accordingly

/assign @stlaz 

@TheRealJon FYI

2024-01-15 12:35 UTC, jhadvig commented
/jira refresh
/cherry-pick release-4.15

2024-01-15 13:22 UTC, stlaz commented
please also include the changes from https://github.com/openshift/library-go/pull/1657

2024-01-15 14:08 UTC, jhadvig commented
> please also include the changes from [openshift/library-go#1657](https://github.com/openshift/library-go/pull/1657)

@stlaz bumping to master

2024-01-15 14:09 UTC, stlaz commented
/lgtm

2024-01-15 18:34 UTC, jhadvig commented
/retest

2024-01-16 09:52 UTC, jhadvig commented
/retest

2024-01-16 10:04 UTC, stlaz requested changes

2024-01-16 10:04 UTC, stlaz commented on pkg/console/operatorclient/operatorclient.go
> +	instance, err := c.Informers.Operator().V1().Consoles().Lister().Get(api.ConfigResourceName)
this is supposed to do a live lookup

2024-01-16 11:16 UTC, stlaz commented
/lgtm

2024-01-16 13:37 UTC, merged