Ocpbugs 27221
openshift/console-operator pull request #837
Opened 2024-01-16 15:09 UTC by jhadvig

Manual backport of https://github.com/openshift/console-operator/pull/836

/assign @stlaz @TheRealJon

2024-01-16 15:29 UTC, jhadvig commented
/hold 
wrong lib-go version

2024-01-17 15:26 UTC, jhadvig commented
/hold cancel

2024-01-17 15:35 UTC, stlaz requested changes

2024-01-17 15:35 UTC, stlaz commented on go.mod
> +	github.com/openshift/api v0.0.0-20231218131639-7a5aa77cc72d
this is a ref to master

2024-01-17 15:35 UTC, stlaz commented on go.mod
> +	github.com/openshift/client-go v0.0.0-20231218140158-47f6d749b9d9
this is a ref to master

2024-01-17 15:35 UTC, stlaz commented on go.mod
> +	k8s.io/api v0.29.0
4.15 is k8s 1.28 IIRC

2024-01-17 17:01 UTC, stlaz commented
/lgtm

2024-01-18 13:49 UTC, jhadvig commented
/retest


Flake
```
--- FAIL: TestLegacyCustomURLWithIngressConsoleComponentRoute (37.10s)
```

2024-01-19 09:56 UTC, jhadvig commented
/retest
/label backport-risk-assessed

2024-01-23 21:38 UTC, merged