OCPBUGS-21029: Bump library-go and golang.org/x/net
openshift/console-operator pull request #850
Opened 2024-01-26 10:47 UTC by jhadvig

/assign @stlaz

2024-01-26 10:49 UTC, jhadvig commented
/jira refresh

2024-01-26 11:39 UTC, stlaz requested changes

2024-01-26 11:39 UTC, stlaz commented on go.mod
> +	k8s.io/api v0.28.2
ocp 4.14 is kube 1.27 (https://access.redhat.com/solutions/4870701)

2024-01-26 13:19 UTC, stlaz commented
/lgtm

2024-01-29 09:26 UTC, jhadvig commented
/retest

2024-02-01 16:56 UTC, jhadvig commented
/retest

2024-02-02 22:11 UTC, jcaianirh commented
/retest

2024-02-08 09:47 UTC, jhadvig commented
/hold

2024-02-09 16:16 UTC, stlaz commented
/lgtm

2024-02-09 19:35 UTC, jhadvig commented
/retest

2024-02-09 19:36 UTC, jhadvig commented
/hold cancel

2024-02-09 19:37 UTC, TheRealJon commented
/label backport-risk-assessed

2024-02-12 10:26 UTC, jhadvig commented
/label backport-risk-assessed
/retest

2024-02-19 13:23 UTC, jerolimov commented
/retitle [release-4.14] OCPBUGS-21029: Bump library-go and golang.org/x/net

2024-02-20 09:00 UTC, yanpzhan commented
/label cherry-pick-approved

2024-02-20 09:05 UTC, merged