[WIP] CONSOLE-4014: Pass OCM organization ID to Segment
openshift/console-operator pull request #889
Opened 2024-04-16 14:15 UTC by jhadvig

WIP WIP WIP

2024-04-22 14:06 UTC, TheRealJon requested changes

2024-04-22 14:06 UTC, TheRealJon commented on pkg/console/subresource/configmap/configmap.go
> -	}
Did we lose this logic?

2024-04-22 14:57 UTC, TheRealJon commented
/lgtm

2024-04-22 16:18 UTC, jhadvig commented
QE Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner

2024-04-22 18:18 UTC, RickJWagner commented
/label px-approved

2024-04-22 20:38 UTC, opayne1 commented
/label docs-approved

2024-04-22 21:24 UTC, jerolimov commented
/retest

2024-04-23 07:43 UTC, jerolimov commented
I got this errors on a cluster bot when enabling monitoring in the cluster-monitoring-config ConfigMap:

https://console/k8s/ns/openshift-monitoring/configmaps/cluster-monitoring-config 

And applying some anntations:

```
E0423 07:29:52.732198 1 status.go:130] ConfigMapSyncDegraded FailedGetTelemetryConfig HTTP request failed with status '403 Forbidden'
E0423 07:29:52.732384 1 base_controller.go:268] ConsoleOperator reconciliation failed: HTTP request failed with status '403 Forbidden'
E0423 07:29:55.008112 1 status.go:130] ConfigMapSyncDegraded FailedGetTelemetryConfig HTTP request failed with status '403 Forbidden'
E0423 07:29:55.008317 1 base_controller.go:268] ConsoleOperator reconciliation failed: HTTP request failed with status '403 Forbidden'
E0423 07:29:57.975301 1 status.go:130] ConfigMapSyncDegraded FailedGetTelemetryConfig HTTP request failed with status '403 Forbidden'
E0423 07:29:57.975600 1 base_controller.go:268] ConsoleOperator reconciliation failed: HTTP request failed with status '403 Forbidden'
```

/hold

2024-04-23 08:10 UTC, jerolimov requested changes

2024-04-23 08:10 UTC, jerolimov commented on pkg/console/telemetry/telemetry.go
> +	client := &http.Client{}
Should we use the http proxy configuration here to ensure that it's working on airgapped clusters?

```suggestion
	client := &http.Client{
		Timeout: 30 * time.Second,
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
		},
	}
```

2024-04-23 10:39 UTC, jhadvig commented
> I got this errors on a cluster bot when enabling monitoring in the cluster-monitoring-config ConfigMap:
> 
> https://console/k8s/ns/openshift-monitoring/configmaps/cluster-monitoring-config
> 
> And applying some anntations:
> 
> ```
> E0423 07:29:52.732198 1 status.go:130] ConfigMapSyncDegraded FailedGetTelemetryConfig HTTP request failed with status '403 Forbidden'
> E0423 07:29:52.732384 1 base_controller.go:268] ConsoleOperator reconciliation failed: HTTP request failed with status '403 Forbidden'
> E0423 07:29:55.008112 1 status.go:130] ConfigMapSyncDegraded FailedGetTelemetryConfig HTTP request failed with status '403 Forbidden'
> E0423 07:29:55.008317 1 base_controller.go:268] ConsoleOperator reconciliation failed: HTTP request failed with status '403 Forbidden'
> E0423 07:29:57.975301 1 status.go:130] ConfigMapSyncDegraded FailedGetTelemetryConfig HTTP request failed with status '403 Forbidden'
> E0423 07:29:57.975600 1 base_controller.go:268] ConsoleOperator reconciliation failed: HTTP request failed with status '403 Forbidden'
> ```
> 
> /hold

Based on the story we dont wanna gather telemetry from CI clusters, so enabling the telemetry on a CI cluster will have it consequences, cause its not supported case.
Im not against handling this case, but if anything lets do it as a followup.

/hold cancel

2024-04-23 20:50 UTC, jhadvig commented
/retest

2024-04-24 06:42 UTC, yapei commented
verified that `CLUSTER_ID` and `ORGANIZATION_ID` can be correctly set in `cm/console-config` and `window.SERVER_FLAGS.telemetry`
/label qe-approved

2024-04-24 09:54 UTC, jerolimov approved these changes

2024-04-24 11:57 UTC, jhadvig commented
flake
```
 ✖  crd-extensions/console-yaml-sample.      01:29        1        -        1        -        - │
  │    cy.ts  
```
/retest

2024-04-24 14:50 UTC, jerolimov commented
/retest

2024-04-24 17:01 UTC, jerolimov commented
/retest

2024-04-24 22:12 UTC, merged